@url = http://localhost:3733

### GET ALL SKILLS
GET {{url}}/skills

### ADD A SKILL
POST {{url}}/skills
Content-Type: application/json

{
"idCode":"111",
"name":"nnn",
"url":"uuu",
"description":"ddd"
}